# Version Control
brew 'git'

# Shell
brew 'zsh'
brew 'tmux'

# Editor
brew 'vim', args: ['with-lua']

# CLI Tools
brew 'jq'
brew 'tig'
brew 'peco'

tap 'caius/jo'
brew 'jo'

brew 'direnv'

tap 'jmespath/jmespath'
brew 'jp'

# Languages
brew 'pyenv'

# Cask
cask 'jetbrains-toolbox'
cask 'docker'
