# Version Control
brew 'git'

# Shell
brew 'zsh'
brew 'zplug'

brew 'tmux'

# Editor
brew 'vim', args: ['with-lua']

# CLI Tools
brew 'jq'
brew 'tig'
brew 'peco'

tap 'caius/jo'
brew 'jo'

brew 'direnv'

tap 'jmespath/jmespath'
brew 'jp'

brew 'awscli'

# For h3poteto/zsh-ec2ssh
tap 'minamijoyo/myaws'
brew 'myaws'

# Cask
cask 'jetbrains-toolbox'
cask 'docker'

# Languages
brew 'pyenv'
brew 'pyenv-virtualenv'
